import type { Metadata } from "next";

import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <div className="flex flex-col ">
        <Navbar className=" dark flex items-center p-4 bg-gradient-to-r from-blue-50 via-purple-100 to-pink-100   w-full" />{" "}
        <div> {children}</div>
      </div>
    </ClerkProvider>
  );
}
